apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-pipeline-app
  template:
    metadata:
      labels:
        app: devops-pipeline-app
    spec:
      containers:
        - name: devops-pipeline-app
          image: imannovv/devops-pipeline-practice:1.0.0-8
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080