apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-practice:1.0.0-12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-pipeline-practice:1.0.0-12
  template:
    metadata:
      labels:
        app: devops-pipeline-practice:1.0.0-12
    spec:
      containers:
        - name: devops-pipeline-practice:1.0.0-12
          image: imannovv/devops-pipeline-practice:1.0.0-12
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
