apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-practice-service
spec:
  selector:
    app: devops-pipeline-practice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
